const LOGIN_DATA = 'LOGIN_DATA';
const IMAGE_URL = 'IMAGE_URL';
const CURRENT_USER = 'CURRENT_USER';
const ALL_USER = 'ALL_USER';
const MESSAGE_LIST = 'MESSAGE_LIST';
const ADMIN_ADD_PRODUCTS = 'ADMIN_ADD_PRODUCTS';

export {
    LOGIN_DATA,
    IMAGE_URL,
    CURRENT_USER,
    ALL_USER,
    MESSAGE_LIST
};